name: Update XP Progress

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update XP Progress Bar
        run: |
          START_DATE=$(date -d "2024-01-01" +%s)
          TODAY=$(date +%s)
          XP=$(( (TODAY - START_DATE) / 86400 % 100 ))
          sed -i "s|https://progress-bar.dev/[0-9]*|https://progress-bar.dev/$XP|g" README.md

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update XP progress bar"
          git push
